[phases.setup]
nixPkgs = ["dotnet-sdk_8_0"]

[phases.install]
cmds = ["dotnet restore GlobalTextSummarizer/GlobalTextSummarizer.csproj"]

[phases.build]
cmds = ["dotnet publish GlobalTextSummarizer/GlobalTextSummarizer.csproj -c Release -o out"]

[start]
cmd = "dotnet out/GlobalTextSummarizer.dll"